/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false --strict-vars=false --env-interface=BuildEnv src/worker-configuration.d.ts` (hash: 0f6fc4a4e7bb0e495938302ac0a27ad9)
interface __BaseEnv_BuildEnv {
	PACKAGES: R2Bucket;
	DB: D1Database;
	ARTIFACTS: Artifacts;
	BUILDER: DurableObjectNamespace<import("./index").Builder>;
	BUILD: Workflow<Parameters<import("./index").BuildMod['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Builder";
	}
	interface PreviewEnv {
		PACKAGES: R2Bucket;
		DB: D1Database;
		ARTIFACTS: Artifacts;
		BUILDER: DurableObjectNamespace<import("./index").Builder>;
		BUILD: Workflow<Parameters<import("./index").BuildMod['run']>[0]['payload']>;
	}
	interface ProductionEnv {
		PACKAGES: R2Bucket;
		DB: D1Database;
		ARTIFACTS: Artifacts;
		BUILDER: DurableObjectNamespace<import("./index").Builder>;
		BUILD: Workflow<Parameters<import("./index").BuildMod['run']>[0]['payload']>;
	}
	interface Env extends __BaseEnv_BuildEnv {}
}
interface BuildEnv extends __BaseEnv_BuildEnv {}
