/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --config=../api/wrangler.toml --include-runtime=false --strict-vars=false src/worker-configuration.d.ts` (hash: 111a57f00f34b26269d854db5f31c60b)
interface __BaseEnv_Env {
  ASSETS: Fetcher;
  ENVIRONMENT: string;
  API_BASE_URL: string;
  ASSETS_BASE_URL: string;
  API: Service<typeof import("../../api/src/index").PublicCatalogEntrypoint>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./worker");
  }
  interface ProductionEnv {
    ASSETS: Fetcher;
    ENVIRONMENT: string;
    API_BASE_URL: string;
    ASSETS_BASE_URL: string;
    API: Service<typeof import("../../api/src/index").PublicCatalogEntrypoint>;
  }
  interface PreviewEnv {
    ASSETS: Fetcher;
    ENVIRONMENT: string;
    API_BASE_URL: string;
    ASSETS_BASE_URL: string;
    API: Service<typeof import("../../api/src/index").PublicCatalogEntrypoint>;
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "ENVIRONMENT" | "API_BASE_URL" | "ASSETS_BASE_URL">
  > {}
}
