/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --env=production --include-runtime=false --strict-vars=false --env-interface=PreviewSyncEnv src/worker-configuration.d.ts` (hash: b359d9de599f0ad9ee242b9d85837cf2)
interface __BaseEnv_PreviewSyncEnv {
	SOURCE_DB: D1Database;
	TARGET_DB: D1Database;
	PREVIEW_SYNC: Workflow<Parameters<import("./index").PreviewSyncWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_PreviewSyncEnv {}
}
interface PreviewSyncEnv extends __BaseEnv_PreviewSyncEnv {}
