/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --include-runtime=false --strict-vars=false --env-interface=QueueEnv src/worker-configuration.d.ts` (hash: 8d423f93b53046a1963eb3b18b60cabb)
interface __BaseEnv_QueueEnv {
	BUCKET: R2Bucket;
	DB: D1Database;
	EMAIL?: SendEmail;
	IMAGES: ImagesBinding;
	ENVIRONMENT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		BUCKET: R2Bucket;
		DB: D1Database;
		EMAIL: SendEmail;
		IMAGES: ImagesBinding;
		ENVIRONMENT: string;
	}
	interface PreviewEnv {
		BUCKET: R2Bucket;
		DB: D1Database;
		IMAGES: ImagesBinding;
		ENVIRONMENT: string;
	}
	interface Env extends __BaseEnv_QueueEnv {}
}
interface QueueEnv extends __BaseEnv_QueueEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT">> {}
}
