/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --env-file=.dev.vars.example --include-runtime=false --strict-vars=false --env-interface=ApiEnv src/worker-configuration.d.ts` (hash: 93ab7662ccdd0195dfec4a4b16641f52)
interface __BaseEnv_ApiEnv {
	BUCKET: R2Bucket;
	DB: D1Database;
	EMAIL?: SendEmail;
	ANALYTICS: AnalyticsEngineDataset;
	PROCESSING_QUEUE: Queue;
	FLAGS: Flagship;
	RATE_LIMIT_API: RateLimit;
	RATE_LIMIT_AUTH: RateLimit;
	RATE_LIMIT_UPLOAD: RateLimit;
	RATE_LIMIT_EDITOR_REPORT: RateLimit;
	RATE_LIMIT_DOWNLOAD_COUNT: RateLimit;
	ENVIRONMENT: string;
	API_BASE_URL: string;
	SITE_BASE_URL: string;
	ASSETS_BASE_URL: string;
	BETTER_AUTH_SECRET: string;
	DISCORD_CLIENT_ID: string;
	DISCORD_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	TWITTER_CLIENT_ID: string;
	TWITTER_CLIENT_SECRET: string;
	TURNSTILE_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface ProductionEnv {
		BUCKET: R2Bucket;
		DB: D1Database;
		EMAIL: SendEmail;
		ANALYTICS: AnalyticsEngineDataset;
		PROCESSING_QUEUE: Queue;
		FLAGS: Flagship;
		RATE_LIMIT_API: RateLimit;
		RATE_LIMIT_AUTH: RateLimit;
		RATE_LIMIT_UPLOAD: RateLimit;
		RATE_LIMIT_EDITOR_REPORT: RateLimit;
		RATE_LIMIT_DOWNLOAD_COUNT: RateLimit;
		ENVIRONMENT: string;
		API_BASE_URL: string;
		SITE_BASE_URL: string;
		ASSETS_BASE_URL: string;
		BETTER_AUTH_SECRET: string;
		DISCORD_CLIENT_ID: string;
		DISCORD_CLIENT_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		TWITTER_CLIENT_ID: string;
		TWITTER_CLIENT_SECRET: string;
		TURNSTILE_SECRET: string;
	}
	interface PreviewEnv {
		BUCKET: R2Bucket;
		DB: D1Database;
		ANALYTICS: AnalyticsEngineDataset;
		PROCESSING_QUEUE: Queue;
		FLAGS: Flagship;
		RATE_LIMIT_API: RateLimit;
		RATE_LIMIT_AUTH: RateLimit;
		RATE_LIMIT_UPLOAD: RateLimit;
		RATE_LIMIT_EDITOR_REPORT: RateLimit;
		RATE_LIMIT_DOWNLOAD_COUNT: RateLimit;
		ENVIRONMENT: string;
		API_BASE_URL: string;
		SITE_BASE_URL: string;
		ASSETS_BASE_URL: string;
		BETTER_AUTH_SECRET: string;
		DISCORD_CLIENT_ID: string;
		DISCORD_CLIENT_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		TWITTER_CLIENT_ID: string;
		TWITTER_CLIENT_SECRET: string;
		TURNSTILE_SECRET: string;
	}
	interface Env extends __BaseEnv_ApiEnv {}
}
interface ApiEnv extends __BaseEnv_ApiEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "API_BASE_URL" | "SITE_BASE_URL" | "ASSETS_BASE_URL" | "BETTER_AUTH_SECRET" | "DISCORD_CLIENT_ID" | "DISCORD_CLIENT_SECRET" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "TWITTER_CLIENT_ID" | "TWITTER_CLIENT_SECRET" | "TURNSTILE_SECRET">> {}
}
